/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package verificador_de_precios;

import java.sql.*;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author aemil
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    private static String codigo = "";
    private static String serverIP = "localhost";
    private static String port = "3306";
    private static String database = "verificador_precios";
    private static String username = "root";
    private static String password = "";
    private static String table = "productos";
    private static Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
    private static String dir = "F:/OneDrive - Universidad de Sonora/Séptimo Semestre/Gestión de la Calidad del Software II/NetBeans/verificador_de_precios/src/verificador_de_precios/images/";

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        
        this.setLayout(null);
        this.setExtendedState(getExtendedState() | JFrame.MAXIMIZED_BOTH);
        this.setVisible(true);
        this.getContentPane().setBackground(new Color(0, 122, 41));
        
        
        pictureLogo.setText("<html><img src='file:" + dir + "logo.png' width='744' height='162'");
        pictureCodebar.setText("<html><img src='file:" + dir + "barcode-scan.gif' width='288' height='252'");
        
        pictureLogo.setLocation(dim.width / 2 - pictureLogo.getWidth() / 2, dim.height / 4 - pictureLogo.getHeight());
        labelTitle.setLocation(dim.width / 2 - labelTitle.getWidth() / 2, dim.height / 3 - pictureLogo.getHeight() / 3);
        labelText.setLocation(dim.width / 2 - labelText.getWidth() / 2, dim.height / 3 - pictureLogo.getHeight() / 3 + labelTitle.getHeight());
        pictureCodebar.setLocation(dim.width / 2 - pictureCodebar.getWidth() / 2, dim.height / 2 + pictureLogo.getHeight());
    }

    /**
     * This method is called from within the constructor to initialize the form
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pictureLogo = new javax.swing.JLabel();
        labelTitle = new javax.swing.JLabel();
        labelText = new javax.swing.JLabel();
        pictureCodebar = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 122, 41));
        setForeground(java.awt.Color.white);
        setUndecorated(true);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        pictureLogo.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pictureLogo.setText("Logo");
        pictureLogo.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelTitle.setFont(new java.awt.Font("Heebo", 1, 150)); // NOI18N
        labelTitle.setForeground(new java.awt.Color(255, 216, 89));
        labelTitle.setText("Checa el precio");
        labelTitle.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        labelText.setFont(new java.awt.Font("Heebo", 1, 80)); // NOI18N
        labelText.setForeground(new java.awt.Color(255, 255, 255));
        labelText.setText("Pasando el código de barras bajo el sensor");
        labelText.setToolTipText("");

        pictureCodebar.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        pictureCodebar.setText("Codebar");
        pictureCodebar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        pictureCodebar.setName(""); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTitle)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(labelText))
                            .addComponent(pictureLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 744, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(pictureCodebar, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(538, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(pictureLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelTitle)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelText)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pictureCodebar, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(204, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyChar() == '\n') {
            String url = "jdbc:mysql://" + serverIP + ":" + port + "/" + database + "?user=" + username + "&pasword=" + password;
            
            try {
                Connection connection = DriverManager.getConnection(url);
                String query = "SELECT producto_nombre, producto_precio, producto_imagen FROM " + database + "." + table + " WHERE producto_codigo = '" + codigo + "';";
                
                ResultSet rs = connection.createStatement().executeQuery(query);
                String nombre = "", precio = "", imagen = "";
                while (rs.next()) {
                    nombre = rs.getString("producto_nombre");
                    precio = rs.getString("producto_precio");
                    imagen = rs.getString("producto_imagen");
                }
                System.out.format("%s, %s, %s", nombre, precio, imagen);
            } catch (SQLException e) {
                System.out.println(e.getMessage());
            }
            codigo = "";
        } else {
            codigo += evt.getKeyChar();
        }
    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
    
    private void MainWindowVisible(boolean option) {
        /***
         * 
         */
        pictureLogo.setVisible(option);
        labelTitle.setVisible(option);
        labelText.setVisible(option);
        pictureCodebar.setVisible(option);
    }
    
    private void PriceWindowVisible(boolean option) {
        
    }
    
    private void ErrorWindowVisible(boolean option) {
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel labelText;
    private javax.swing.JLabel labelTitle;
    private javax.swing.JLabel pictureCodebar;
    private javax.swing.JLabel pictureLogo;
    // End of variables declaration//GEN-END:variables
}
